### ISSUE TITLE
CI breaks on llvm install since recently

### ISSUE THREAD

**Issue by christianparpart** [whisperity/codechecker-analysis-action#2]
Most likely something on the remote end has changed.

I am using llvm_version `latest`. Not sure if non-latest break, too. 

What would be a good version value? Just the major or the full triple? (Maybe a good example could be added to the readme for such a case).

**Comment by whisperity** [comment]
Confirmed and it seems we're converging... Something changed with the GitHub base image. I would very much like to rant AGAIN about the fact that they supply pre-filled images that are not pure versions of the OS you're targeting, but whatever... The alternatives system now has a top-level entry named `clang-tidy`... Most likely because they install a newer package (`clang-11` as opposed to just `clang`?) by default and that package, supplied by Ubuntu, has the hooks for the alternatives system. (The PPA packages do not.)

```
Name: clang
  Link: /usr/bin/clang
  Status: auto
  Best: /usr/bin/clang-11
  Value: /usr/bin/clang-11
  
  Alternative: /usr/bin/clang-11
  Priority: 100
  Name: clang-tidy
  Link: /usr/bin/clang-tidy
  Status: auto
  Best: /usr/bin/clang-tidy-11
  Value: /usr/bin/clang-tidy-11
  
  Alternative: /usr/bin/clang-tidy-11
  Priority: 100
```

Seems like an easy fix, give me a minute. :wink:

**Comment by christianparpart** [comment]
Thanks @whisperity !
